import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// Sidebar order/labels come from _category_.json files and sidebar_position
// front matter inside docs/.
const sidebars: SidebarsConfig = {
  docs: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;
